apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yaml
- service.yaml
namespace: myapp
images:
- name: demo-frontend
  newName: caocr/demo-frontend
  newTag: master-9f040540-1722065188
