apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yaml
- service.yaml
namespace: myapp-service
images:
- name: demo-frontend
  newName: caocr/demo-frontend
  newTag: master-9b51bc69-1722064725
