name: Build Docker Image
on:
  push:
    branches:
    - "master"
env:
  CONTAINER_NAME: demo-frontend
  DOCEKRHUB_REGISTRY: caocr

jobs:
  build-and-deploy:
    name: push docker image to docker hub
    runs-on: ubuntu-latest
    concurrency:
      group: build-and-deploy
      cancel-in-progress: true
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Prepare
      id: prep
      run: |
        BRANCH=${GITHUB_REF##*/}
        TS=$(date +%s)
        REVISION=${GITHUB_SHA::8}
        BUILD_ID="${BRANCH}-${REVISION}-${TS}"
        LATEST_ID=canary
        echo ::set-output name=BUILD_DATE::$(date -u +'%Y-%m-%dT%H:%M:%SZ')
        echo ::set-output name=BUILD_ID::${BUILD_ID}
        echo ::set-output name=LATEST_ID::${LATEST_ID}
    - name: login to docker hub
      id: docker-hub
      env:
        username: ${{secrets.DOCKERHUB_USERNAME}}
        password: ${{secrets.DOCKERHUB_PASSWORD}}
      run: "docker login -u $username -p $password \n"

    - name: build, tag, push the docker image
      id: build-docker-image
      env:
        DOCKERHUB_REPOSITORY: ${{ env.CONTAINER_NAME }}
        BUILD_ID: ${{ steps.prep.outputs.BUILD_ID }}
        LATEST_ID: ${{ steps.prep.outputs.LATEST_ID }}
        NEXT_ENV: development
      run: |
        docker build --build-arg NEXT_ENV=$NEXT_ENV -t $DOCEKRHUB_REGISTRY/$DOCKERHUB_REPOSITORY:$BUILD_ID -t $DOCEKRHUB_REGISTRY/$DOCKERHUB_REPOSITORY:$LATEST_ID .
        docker push $DOCEKRHUB_REGISTRY/$DOCKERHUB_REPOSITORY --all-tags
        echo "::set-output name=image::$DOCEKRHUB_REGISTRY/$DOCKERHUB_REPOSITORY:$BUILD_ID"
    - name: Image digest
      run: echo ${{ steps.build-docker-image.outputs.image }}

    #######
    ## Auto-deploy to Dev Environment
    #######
    - name: Setup Kustomize
      uses: imranismail/setup-kustomize@v1
      with:
        kustomize-version: "3.6.1"

    - name: Pull changes
      run: |
        git pull

    - name: Update Kubernetes resources for dev
      run: |
        cd kubernetes/dev/
        kustomize edit set image ${{ env.CONTAINER_NAME }}=${{ steps.build-docker-image.outputs.image }}
        cat kustomization.yaml

    - uses: stefanzweifel/git-auto-commit-action@v4
      name: Bump version
      with:
        commit_message: Auto-deploy to dev (via gitops)



